@startuml SimpleReadSession
participant User as U
participant Client as C
participant RestAPI as R
participant Mesh as M
participant MeshSession as S
participant DB as D
U -> C : Start task
activate C
group Simple read session
== Initialize ==
C -> R : CreateSession
activate R
R -> M
activate M
M -> S : Create a new session
activate S
R <-- M
deactivate M
C <-- R : <SessionID>
deactivate R
== Do operation(s) ==
C -> R : ReadTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Read data from session cache
S --> D : Fetch data if not in the cache
activate D
S <-- D
deactivate D
M <-- S
R <-- M
deactivate M
C <-- R : <Time series values>
deactivate R
== End ==
C -> R : EndSession(<SessionID>)
activate R
R -> M
activate M
M --> S : Terminate session
M <-- S
deactivate S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Completed ==
end
U <- C : Done
deactivate C
@enduml
@startuml LongRunningReadSession
participant User as U
participant Client as C
participant RestAPI as R
participant Mesh as M
participant MeshSession as S
participant DB as D
U -> C : Start task
group Long running read session
activate C
== Initialize ==
C -> R : CreateSession
activate R
R -> M
activate M
M -> S : Create a new session
activate S
R <-- M
deactivate M
C <-- R : <SessionID>
deactivate R
== Do operation(s) ==
C -> R : ReadTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Read data from session cache
S --> D : Fetch data if not in the cache
activate D
S <-- D
deactivate D
M <-- S
R <-- M
deactivate M
C <-- R : <Time series values>
deactivate R
... Do several operations ...
... If close to 5 minutes since last operation ...
C -> R : ExtendSession(<SessionId)
activate R
R -> M : Extend session time out
activate M
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
... Do more operations ...
C -> R : ReadTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Read data from session cache
S --> D : Fetch data if not in the cache
activate D
S <-- D
deactivate D
M <-- S
R <-- M
deactivate M
C <-- R : <Time series values>
deactivate R
== End ==
C -> R : EndSession(<SessionID>)
activate R
R -> M
activate M
M --> S : Terminate session
M <-- S
deactivate S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Completed ==
end
U <- C : Done
deactivate C
@enduml
@startuml SimpleWriteSessionCommit
participant User as U
participant Client as C
participant RestAPI as R
participant Mesh as M
participant MeshSession as S
participant DB as D
U -> C : Start task
activate C
group Simple session doing updates
== Initialize ==
C -> R : CreateSession
activate R
R -> M
activate M
M -> S : Create a new session
activate S
R <-- M
deactivate M
C <-- R : <SessionID>
deactivate R
== Do operation(s) ==
C -> R : WriteTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Write data to session cache
M <-- S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Commit changes ==
C -> R : Commit(<SessionID>)
activate R
R -> M
activate M
M -> S : Get changes from session cache
activate S
M <-- S : <changes>
deactivate S
M -> D : Update database and commit
activate D
M <-- D
deactivate D
R <-- M
deactivate 
C <-- R : <ok>
== End ==
C -> R : EndSession(<SessionID>)
activate R
R -> M
activate M
M --> S : Terminate session
M <-- S
deactivate S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Completed ==
end
U <- C : Done
deactivate C
@enduml
@startuml SimpleWriteSessionRollback
participant User as U
participant Client as C
participant RestAPI as R
participant Mesh as M
participant MeshSession as S
participant DB as D
U -> C : Start task
activate C
group Simple session doing updates
== Initialize ==
C -> R : CreateSession
activate R
R -> M
activate M
M -> S : Create a new session
activate S
R <-- M
deactivate M
C <-- R : <SessionID>
deactivate R
== Do operation(s) ==
C -> R : WriteTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Write data to session cache
M <-- S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Cancel/rollback changes ==
C -> R : Rollback(<SessionID>)
activate R
R -> M
activate M
M -> S : Remove changes from session cache
activate S
M <-- S : <ok>
deactivate S
R <-- M
deactivate 
C <-- R : <ok>
== End ==
C -> R : EndSession(<SessionID>)
activate R
R -> M
activate M
M --> S : Terminate session
M <-- S
deactivate S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Completed ==
end
U <- C : Done
deactivate C
@enduml
@startuml LongRunningWriteSession
participant User as U
participant Client as C
participant RestAPI as R
participant Mesh as M
participant MeshSession as S
participant DB as D
U -> C : Start task
group Long running write session
activate C
== Initialize ==
C -> R : CreateSession
activate R
R -> M
activate M
M -> S : Create a new session
activate S
R <-- M
deactivate M
C <-- R : <SessionID>
deactivate R
== Do operation(s) ==
C -> R : WriteTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Write data to session cache
M <-- S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
... Do several operations, and save changes to storage ...
C -> R : WriteTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Write data to session cache
M <-- S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
C -> R : Commit(<SessionID>)
activate R
R -> M
activate M
M -> S : Get changes from session cache
activate S
M <-- S : <changes>
deactivate S
M -> D : Update database and commit
activate D
M <-- D
deactivate D
R <-- M
deactivate 
C <-- R : <ok>
deactivate R
... If close to 5 minutes since last operation ...
C -> R : ExtendSession(<SessionId)
activate R
R -> M : Extend session time out
activate M
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
... Do more operations, and save changes to storage ...
C -> R : WriteTimeSeriesValues(<request params>,<SessionID>)
activate R
R -> M
activate M
M --> S : Write data to session cache
M <-- S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
C -> R : Commit(<SessionID>)
activate R
R -> M
activate M
M -> S : Get changes from session cache
activate S
M <-- S : <changes>
deactivate S
M -> D : Update database and commit
activate D
M <-- D
deactivate D
R <-- M
deactivate 
C <-- R : <ok>
deactivate R
== End ==
C -> R : EndSession(<SessionID>)
activate R
R -> M
activate M
M --> S : Terminate session
M <-- S
deactivate S
R <-- M
deactivate M
C <-- R : <ok>
deactivate R
== Completed ==
end
U <- C : Done
deactivate C
@enduml