syntax = "proto3";

package volue.mesh.grpc.allocate_reserves.v1alpha;

import "type/resources.proto";

service AllocateReservesService {

  // Trigger AllocateReserves.
  // This function can be used to distribute values
  // on a reserves time series onto a set of target time series
  // based on capacity and priority information.
  // For example, distribute a total requested production
  // onto production units.
  rpc AllocateReserves(AllocateReservesRequest) returns (AllocateReservesResponse) {}
}

message AllocateReservesRequest {
  volue.mesh.grpc.type.Guid session_id = 1;

  // The request interval.
  volue.mesh.grpc.type.UtcInterval interval = 2;

  // An ID of the object in the model that will
  // be used as a start point of the searches.
  volue.mesh.grpc.type.MeshId start_object = 3;

  // A search expression that defines the set of objects
  // that participate in the distribution of the total value.
  string objects_search_expression = 4;

  // A search expression to find a fixed resolution time series
  // with the requested total value to distribute.
  string total_time_series_search_expression = 5;

  // The name of the time series attribute on the participating
  // Mesh object that contains a time series with priority values.
  string priority_time_series_attribute_name = 6;

  // The name of the time series attribute on the participating
  // Mesh object that contains a time series with capacity values.
  string capacity_time_series_attribute_name = 7;

  // The name of the time series attribute on the participating
  // Mesh object that contains a time series to receive the result values.
  // This attribute has to be connected to the time series entry
  // of the same resolution as the total request time series attribute.
  string allocated_time_series_attribute_name = 8;
}

message AllocateReservesResponse {}
